language: rust
rust:
  - nightly

cache: cargo

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran libopenblas-dev

script:
  - cargo build --verbose
  - cargo test --verbose